language: python

sudo: false

os:
  - linux

python:
  - '2.6'
  - '2.7'
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6.0b1'
  - pypy
  - pypy3

install:
  - pip install -U pip
  - pip install -U tox-travis
  - pip install python-coveralls
  - pip install coverage

script:
  - tox -v --recreate

after_success:
  - coveralls

before_deploy:
  - pip install twine
  - pip install wheel
  - python setup.py sdist bdist_wheel

deploy:
    provider: script
    script: pypi_deploy.sh
    on:
        branch: master
        tags: true
        python: '3.4'
